export const GET_CAMERA_LIST = "GET_CAMERA_LIST"
export const SET_CAMERA_SELECT = "SET_CAMERA_SELECT"

export const GET_THUMBNAIL_LIST = "GET_THUMBNAIL_LIST"
export const SELECT_THUMBNAIL_GROUP = "SELECT_THUMBNAIL_GROUP"
export const OVER_THUMBNAIL_GROUP = "OVER_THUMBNAIL_GROUP"
export const START_TIME_GROUP = "START_TIME_GROUP"
export const GET_SUBTHUMBNAILS_LIST = "GET_SUBTHUMBNAILS_LIST"
export const SET_ENDTIME = "SET_ENDTIME"
export const GET_SEARCH_TIME = "GET_SEARCH_TIME"

export const VIDEO_LIVE_MODE = "VIDEO_LIVE_MODE"
export const VIDEO_VOD_MODE = "VIDEO_VOD_MODE"